keymap = {
    'Key_Comma': ',',
    'Key_SemiColon': ';',
    'Key_LeftAlt': 'Left Alt',
    'Key_LeftBracket': '[',
    'Key_LeftControl': 'Left Ctrl',
    'Key_LeftShift': 'Left Shift',
    'Key_Minus': '-',
    'Key_Plus': '+',
    'Key_Equals': '=',
    'Key_Period': '.',
    'Key_RightAlt': 'Right Alt',
    'Key_RightBracket': ']',
    'Key_RightControl': 'Right Ctrl',
    'Key_RightShift': 'Right Shift',
    'Key_RightArrow': 'Right',
    'Key_UpArrow': 'Up',
    'Key_LeftArrow': 'Left',
    'Key_DownArrow': 'Down',
    'Key_LessThan': '<',
    'Key_GreaterThan': '>',
    'Key_LeftParenthesis': '(',
    'Key_RightParenthesis': ')',
    'Key_Numpad_0': 'Num 0',
    'Key_Numpad_1': 'Num 1',
    'Key_Numpad_2': 'Num 2',
    'Key_Numpad_3': 'Num 3',
    'Key_Numpad_4': 'Num 4',
    'Key_Numpad_5': 'Num 5',
    'Key_Numpad_6': 'Num 6',
    'Key_Numpad_7': 'Num 7',
    'Key_Numpad_8': 'Num 8',
    'Key_Numpad_9': 'Num 9',
    'Key_Numpad_Decimal': 'Num .',
    'Key_Numpad_Multiply': 'Num *',
    'Key_Numpad_Divide': 'Num /',
    'Key_Numpad_Add': 'Num +',
    'Key_Numpad_Subtract': 'Num -',
    'Key_Numpad_Enter': 'Num Enter',
    'Key_Numpad_Equals': 'Num =',
    'Key_Numpad_Comma': 'Num ,',
    'Key_Numpad_Period': 'Num .',
    'Key_PageDown': 'PgDn',
    'Key_PageUp': 'PgUp',
    'Key_Grave': '`',
    'Key_BackSlash': '\\',
    'Key_Slash': '/',
    'Key_Apostrophe': '\'',
    'Key_Hash': '#',
}
