from collections import OrderedDict


supportedDevices = OrderedDict([
    ('HotasCougar',{'Template': 'hotascougar', 'HandledDevices': ['044F0400']}),
    ('LogitechExtreme3DPro', {'Template': 'extreme3dpro', 'HandledDevices': ['LogitechExtreme3DPro']}),
    ('Logitech710WirelessGamepad', {'Template': 'f710', 'HandledDevices': ['Logitech710WirelessGamepad']}),
    ('LogitechGTWheel', {'Template': 'gtwheel', 'HandledDevices': ['046DC29A']}),
    ('LogitechG940', {'Template': 'g940', 'HandledDevices': ['LogitechG940Joystick', 'LogitechG940Throttle']}),
    ('T16000M', {'Template': 't16000m', 'HandledDevices': ['T16000M']}),
    ('T16000MFCS', {'Template': 't16000mfcs', 'HandledDevices': ['T16000MFCS', 'T16000MTHROTTLE']}),
    ('TFlightHOTASX', {'Template': 'hotasx', 'HandledDevices': ['ThrustMasterTFlightHOTASX']}),
    ('ThrustMasterHOTAS4', {'Template': 'hotas4', 'HandledDevices': ['ThrustMasterHOTAS4']}),
    ('T-Rudder', {'Template': 'tfrp', 'HandledDevices': ['T-Rudder']}),
    ('TFlightStickX', {'Template': 'stickx', 'HandledDevices': ['044FB106']}),
    ('Warthog', {'Template': 'warthog', 'HandledDevices': ['ThrustMasterWarthogJoystick', 'ThrustMasterWarthogThrottle', 'ThrustMasterWarthogCombined']}),
    ('CobraM5', {'Template': 'cobram5', 'HandledDevices': ['11C05603', '11C05605']}),
    ('Gladiator', {'Template': 'gladiator', 'HandledDevices': ['231D0121']}),
    ('Cougar', {'Template': 'cougar', 'HandledDevices': ['044FB351', '044FB352']}),
    ('SaitekFLY5', {'Template': 'fly5', 'HandledDevices': ['SaitekFLY5', '06A30836']}),
    ('SaitekX45', {'Template': 'x45', 'HandledDevices': ['SaitekX45']}),
    ('SaitekX52', {'Template': 'x52', 'HandledDevices': ['SaitekX52']}),
    ('SaitekX52Pro', {'Template': 'x52pro', 'HandledDevices': ['SaitekX52Pro']}),
    ('SaitekX55', {'Template': 'x55', 'HandledDevices': ['SaitekX55Joystick', 'SaitekX55Throttle']}),
    ('SaitekX56', {'Template': 'x56', 'HandledDevices': ['SaitekX56Joystick', 'SaitekX56Throttle', '07382221', '0738A221']}),
    ('SaitekProFlightPedals', {'Template': 'proflightpedals', 'HandledDevices': ['SaitekProFlightRudderPedals', '06A30765']}),
    ('SaitekProFlightCombatPedals', {'Template': 'proflightcombatpedals', 'HandledDevices': ['SaitekProFlightCombatRudderPedals']}),
    ('CHFighterStick', {'Template': 'chfighter', 'KeyDevices': ['CHFighterStick', '068EC0F3'], 'HandledDevices': ['CHFighterStick', '068EC0F3', 'CHProThrottle1', 'CHProThrottle2', '068EC010']}),
    ('CHCombatStick', {'Template': 'chcombat', 'KeyDevices': ['CHCombatStick'], 'HandledDevices': ['CHCombatStick', 'CHProThrottle1', 'CHProThrottle2', '068EC010']}),
    ('CHProThrottle', {'Template': 'chfighter', 'HandledDevices': ['CHProThrottle1', 'CHProThrottle2', '068EC010']}),
    ('CHThrottleQuadrant', {'Template': 'chquadrant', 'HandledDevices': ['068E00FA']}),
    ('CHProFlightThrottleQuadrant', {'Template': 'chproflightquadrant', 'HandledDevices': ['06A30C2D']}),
    ('CHProPedals', {'Template': 'chpropedals', 'HandledDevices': ['CHProPedals', '068E00F2']}),
    ('SidePanelControlDeck', {'Template': 'sidepanelcontroldeck', 'HandledDevices': ['07382218']}),
    ('XBox', {'Template': 'xbox', 'HandledDevices': ['XB360 Pad', '045E02FF', '045E02DD']}),
    ('XBoxElite', {'Template': 'xboxelite', 'HandledDevices': ['045E02E3']}),
    ('GamePad', {'Template': 'xbox', 'HandledDevices': ['GamePad']}),
    ('Sabretooth', {'Template': 'sabretooth', 'HandledDevices': ['1689FE00']}),
    ('LogitechG940Pedals', {'Template': 'g940pedals', 'HandledDevices': ['LogitechG940Pedals']}),
    ('SlawBF109Pedals', {'Template': 'slawbf109pedals', 'HandledDevices': ['SlawFlightControlRudder']}),
    ('MFGCrosswind', {'Template': 'crosswind', 'HandledDevices': ['16D00A38', '85640203']}),
    ('DS4', {'Template': 'ds4', 'HandledDevices': ['DS4', 'DualShock4']}),
    ('VPC-WarBRD-DELTA-Left', {'Template': 'vpc-warbrd-delta-left', 'HandledDevices': ['03EB2042']}),
    ('VPC-WarBRD-DELTA-Right', {'Template': 'vpc-warbrd-delta-right', 'HandledDevices': ['03EB2044']}),
    ('VPC-ALPHA-Left', {'Template': 'vpc-alpha-left', 'HandledDevices': ['03EB2046']}),
    ('VPC-ALPHA-Right', {'Template': 'vpc-alpha-right', 'HandledDevices': ['03EB2048']}),
    ('VPC-ALPHA-Left-Custom', {'Template': 'vpc-alpha-left', 'HandledDevices': ['03EB9901']}),
    ('VPC-ALPHA-Right-Custom', {'Template': 'vpc-alpha-right', 'HandledDevices': ['03EB9902']}),
    ('VKB-Kosmosima-SCG-Left', {'Template': 'vkb-kosmosima-scg-left', 'HandledDevices': ['231D0127']}),
    ('VKB-Kosmosima-SCG-Right', {'Template': 'vkb-kosmosima-scg-right', 'HandledDevices': ['231D0126']}),
    ('VKB-Gladiator-NXT-Premium-Right', {'Template': 'vkb-gladiator-nxt-premium-right', 'HandledDevices': ['231D0200']}),
    ('VKB-Gladiator-NXT-Premium-Left', {'Template': 'vkb-gladiator-nxt-premium-left', 'HandledDevices': ['231D0201']}),
    ('Keyboard', {'Template': 'keyboard', 'HandledDevices': ['Keyboard']})
])
